### Test static file

GET http://localhost:8080/localhost:8080/


### Test static file with tower-http
GET http://localhost:8080/fixtures

### test 2
GET http://localhost:8080/fixtures/blake3.txt

### test

GET http://baidu.com/
